local State = {}
local I18n = require("src.core.i18n.i18n")
local BackgroundThemeCatalog = require("src.core.backgrounds.themes.background_theme_catalog")
local ThemeCatalog = require("src.features.gameplay.card_themes.theme_catalog")

local function buildCardThemeConfig(user_profile)
    local settings = (user_profile and user_profile.card_settings) or {}

    return {
        theme_id = ThemeCatalog.normalizeThemeId(settings.theme_id),
        high_contrast = settings.high_contrast == true,
        back_id = settings.back_id or "classic_grid",
        wildcard_card = nil,
    }
end

function State.create(room_id, user_profile, initial_game)
    return {
        room_id = room_id,
        steam_id = user_profile.steam_id,
        nickname = user_profile.nickname,
        avatar_id = user_profile.avatar_id or "avatar_1",
        accessories = user_profile.accessories or { owned_item_ids = {}, equipped = {} },
        card_theme_config = buildCardThemeConfig(user_profile),
        loading = false,
        fatal_error_message = "",
        toast_message = "",
        toast_remaining = 0,
        toast_duration = 0,
        status_message = I18n:t("gameplay.loading_status"),
        game = initial_game or nil,
        single_player_bot_avatar_by_seat = {},
        ui_phase = "loading",
        tribute_overlay_remaining = 0,
        tribute_notice_remaining = 0,
        tribute_countdown_remaining = 0,
        tribute_countdown_duration = 0,
        tribute_force_visible = false,
        tribute_overlay_snapshot = nil,
        turn_countdown_remaining = 0,
        turn_countdown_duration = 0,
        turn_countdown_pending_remaining = 0,
        turn_countdown_pending_duration = 0,
        arrange_hold_visible = false,
        arrange_zero_hold = false,
        arrange_progress_request_active = false,
        arrange_progress_request_elapsed = 0,
        wildcard_overlay_remaining = 0,
        deal_overlay_remaining = 0,
        deal_overlay_duration = 0,
        deal_sfx_start_remaining = 0,
        hand_loading_remaining = 0,
        hand_loading_duration = 0,
        arrange_remaining = 0,
        reveal_cards = false,
        selected_card_ids = {},
        pinned_card_ids = {},
        pinned_card_groups = {},
        hovered_card_id = nil,
        hovered_control = nil,
        selected_tribute_card_id = nil,
        hovered_tribute_card_id = nil,
        hovered_tribute_control = nil,
        show_round_info_overlay = false,
        round_info_active_tab = "history",
        hovered_round_info_button = false,
        hovered_round_info_overlay_control = nil,
        hand_history_scroll = 0,
        play_history_hand_no = nil,
        play_history_last_seen_signature = "",
        play_history_entries = {},
        play_history_signatures = {},
        hovered_debug_button = false,
        hovered_settings_button = false,
        hovered_settings_control = nil,
        hovered_player_hud_role = nil,
        show_player_profile_overlay = false,
        hovered_player_profile_control = nil,
        profile_overlay_player = nil,
        pass_markers = {},
        realtime_status = "disconnected",
        realtime_hint_message = "",
        realtime_last_bridge_error_signature = "",
        game_snapshot_request_elapsed = 0,
        game_snapshot_request_attempts = 0,
        realtime_snapshot_watchdog_elapsed = 0,
        action_waiting = false,
        suppress_next_pass_sfx = false,
        last_play = nil,
        next_command_seq = 1,
        settlement_countdown_remaining = 0,
        settlement_countdown_duration = 0,
        result_transition_remaining = 0,
        result_transition_duration = 0,
        remaining_cards_reveal_remaining = 0,
        remaining_cards_reveal_duration = 0,
        remaining_cards_intro_remaining = 0,
        remaining_cards_intro_duration = 0,
        remaining_cards_countdown_remaining = 0,
        remaining_cards_countdown_duration = 0,
        result_revealed_hands = nil,
        remaining_cards_button_hovered = false,
        hand_count_alerts = {},
        settlement_button_hovered = false,
        rematch_confirm_button_hovered = false,
        rematch_leave_button_hovered = false,
        button_press_feedback = {
            play_cards = 0,
            pass_turn = 0,
        },
        pending_button_action = nil,
        pending_button_action_timer = 0,
        pending_button_action_progress = 0,
        last_settlement_hand_no = nil,
        last_settlement_audio_hand_no = nil,
        settings_overlay_visible = false,
        confirm_dialog_visible = false,
        confirm_dialog_action = nil,
        hovered_confirm_dialog_control = nil,
        settings_tab = "display_audio",
        settings_window_mode = "windowed",
        settings_language_options = {},
        settings_language_index = 1,
        settings_resolution_options = {},
        settings_resolution_index = 1,
        settings_fps_options = {},
        settings_fps_index = 1,
        settings_volume_options = {},
        settings_game_volume_index = 1,
        settings_bgm_volume_index = 1,
        settings_game_bgm_options = {
            "game_default",
            "bgm1",
            "bgm2",
            "bgm3",
            "bgm4",
            "bgm5",
        },
        settings_game_bgm_index = 1,
        settings_background_theme_id = BackgroundThemeCatalog.DEFAULT_THEME_ID,
        settings_background_preview_theme_id = nil,
        settings_background_preview_seed = nil,
        settings_background_theme_options = BackgroundThemeCatalog.OPTIONS,
        settings_card_theme_options = ThemeCatalog.OPTIONS,
        settings_card_theme_index = 1,
        settings_card_back_options = {
            "classic_grid",
            "emerald_lattice",
            "crimson_fan",
            "violet_tile",
            "midnight_star",
        },
        settings_card_back_index = 1,
        server_loading_visible = false,
        server_loading_message = nil,
        server_loading_elapsed = 0,
        server_loading_request_started = false,
        pending_server_action = nil,
        card_settings_dirty = false,
        audio_mute_master = false,
    }
end

return State
